ekf_filter_node:
  ros__parameters:
    frequency: 50.0  # Frequency of the EKF updates
    sensor_timeout: 0.1
    two_d_mode: true  # Use 2D localization (x, y, yaw) only
    transform_time_offset: 0.0
    transform_timeout: 0.0

    # Frame IDs
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Sensor input configurations
    odom0: /odom
    odom0_config: [true, true, false,  # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   true, true, false,   # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw
                   false, false, false] # ax, ay, az

    imu0: /imu
    imu0_config: [false, false, false,  # x, y, z
                  true, true, true,     # roll, pitch, yaw
                  false, false, false,  # vx, vy, vz
                  false, false, true,   # vroll, vpitch, vyaw
                  false, false, false]  # ax, ay, az
    imu0_differential: false
    imu0_relative: true

    # Process noise
    process_noise_covariance:   [0.01, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # x
                                  0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # y
                                  0.0,    0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # z
                                  0.0,    0.0,    0.0,    0.1,  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # roll
                                  0.0,    0.0,    0.0,    0.0,    0.1,  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # pitch
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # yaw
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # vx
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # vy
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  # vz
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.1,  0.0,    0.0,    0.0,    0.0,    0.0,  # vroll
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.1,  0.0,    0.0,    0.0,    0.0,  # vpitch
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.05, 0.0,    0.0,    0.0,  # vyaw
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.1,  0.0,    0.0,  # ax
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.1,  0.0,  # ay
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.1] # 