### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 100.0

        two_d_mode: true

        publish_tf: true

        odom_frame: odom           
        base_link_frame: base_link  
        world_frame: odom           

        odom0: /odom
        odom0_config: [false, false,  false,
                       false, false, true,
                       true, true, false,
                       false, false, true,
                       false, false, false]

        odom0_differential: false
        odom0_relative: true

        imu0: /imu/z
        imu0_config: [false, false, false,
                      false,  false,  true,
                      false, false, false,
                      false,  false,  true,
                      true,  false,  false]
        
        imu0_differential: false
        imu0_relative: true